"""add_duration_and_deadline_to_sessions

Revision ID: 237547933056
Revises: ce70ee9633d9
Create Date: 2026-03-07 10:40:52.423242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237547933056'
down_revision: Union[str, Sequence[str], None] = 'ce70ee9633d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_sessions', sa.Column('duration_hours', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('report_sessions', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('report_sessions', sa.Column('deadline_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_sessions', 'deadline_at')
    op.drop_column('report_sessions', 'start_at')
    op.drop_column('report_sessions', 'duration_hours')
    # ### end Alembic commands ###
